name: default_experiment
task: null
exclude_task: null
solver: null
benchmark: null
timeout: 600
repetitions: 1
result_format: csv
plot: null
grouping: ['tag', 'task', 'benchmark_id', 'solver_id']
save_to: null
statistics: null
score: null
printing: default
copy_raws: False
table_export: ['txt']
archive: null
save_output: True
archive_output: null
status_file_path: null
time_measurement: default
validation:
  mode: null
  plot: null
  table_export: null
significance:
  parametric_test: null
  parametric_post_hoc: null
  non_parametric_test: null
  non_parametric_post_hoc: null
  p_adjust: null
  plot: null
  table_export: null