name: default_experiment
task: null
exclude_task: null
solver: null
benchmark: null
timeout: 600
repetitions: 1
result_format: csv
plot: null
grouping: ['tag', 'task', 'benchmark_id', 'solver_id']
save_to: null
statistics: null
printing: default
copy_raws: True
table_export: ['txt']
archive: null
save_output: True
archive_output: null